//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roga
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE_
    {
        public int ID { get; }
        public byte[] img { get; set; }
        public int userid { get; set; }
    
        public virtual USER_ USER_ { get; set; }
    }
}
